Update load, power, throughput usage and option parsing
Prepare for future use of long option handling.

diff --git a/scripts/dbt7-throughput-test.in b/scripts/dbt7-throughput-test.in
--- a/scripts/dbt7-throughput-test.in
+++ b/scripts/dbt7-throughput-test.in
@@ -12,24 +12,30 @@ PROFILE=0
 
 usage()
 {
-	echo "Usage: `basename $0` is the DBT-7 Throughput Test"
-	echo ""
-	echo "Usage:"
-	echo "  `basename $0` [OPTION]"
-	echo ""
-	echo "Options:"
-	echo "  -a DBMS          database management system: pgsql"
-	echo "  -d DIALECT       dialect override"
-	echo "  -o PATH          path to save results"
-	echo "  -i INPUT         input override, default $INPUT"
-	echo "  -n STREAMS       number of streams"
-	echo "  -r               restart database, if already running"
-	echo "  -s SCALE         scale factor, default $SCALE"
-	echo "  -U               run test as an unprivileged user"
-	echo "  -Y               enable profiling"
-	echo ""
-	echo "PostgreSQL options (pgsql):"
-	echo "  -p PARAMETERS    PostgreSQL parameters"
+	cat << EOF
+$(basename "${0}") is the Database Test 7 (DBT-7) power tester
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -a DBMS          database management system: pgsql
+  -d DIALECT       dialect override
+  -o PATH          path to save results
+  -i INPUT         input override, default $INPUT
+  -n STREAMS       number of streams
+  -r               restart database, if already running
+  -s SCALE         scale factor, default $SCALE
+  -U               run test as an unprivileged user
+  -V, --version    output version information, then exit
+  -Y               enable profiling"
+  -?, --help       show this help, then exit
+
+PostgreSQL options (pgsql):
+  -p PARAMETERS    PostgreSQL parameters
+
+@HOMEPAGE@
+EOF
 }
 
 run_data_maintenance()
@@ -81,51 +87,70 @@ run_queries()
 	echo "**`date` throughput test $NUM completed ($DIFF_TIME seconds)**"
 }
 
-while getopts "a:d:hi:n:o:p:r:s:S:UY" OPT; do
-	case $OPT in
-	a)
-		DATABASE=$OPTARG
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-a)
+		shift
+		DATABASE="${1}"
 		;;
-	d)
-		DIALECT=$OPTARG
+	(-d)
+		shift
+		DIALECT="${1}"
 		;;
-	h)
-		usage
-		exit 0
+	(-n)
+		shift
+		STREAMS="${1}"
 		;;
-	n)
-		STREAMS=$OPTARG
+	(-i)
+		shift
+		INPUT="${1}"
 		;;
-	i)
-		INPUT=$OPTARG
-		;;
-	o)
-		OUTPUT_DIR=$OPTARG
+	(-o)
+		shift
+		OUTPUT_DIR="${1}"
 		mkdir -p $OUTPUT_DIR
 		;;
-	p)
-		PARAMETERS_ARG="-p \"$OPTARG\""
+	(-p)
+		shift
+		PARAMETERS_ARG="-p \"${1}\""
 		;;
-	r)
+	(-r)
 		RESTART=1
 		;;
-	s)
-		SCALE=$OPTARG
+	(-s)
+		shift
+		SCALE="${1}"
 		;;
-	S)
-		SEED_FILE=$OPTARG
+	(-S)
+		shift
+		SEED_FILE="${1}"
 		;;
-	U)
+	(-U)
 		PRIVILEGED=0
 		PRIVILEGED_ARG="-U"
 		;;
-	Y)
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 7) v@PROJECT_VERSION@"
+		;;
+	(-Y)
 		PROFILE=1
 		LINUXPERF_FLAG="-Y"
 		;;
-	\?) exit 1
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
 		;;
 	esac
+	shift
 done
 
 if [ "x${DATABASE}" = "x" ]; then
