Do not general pdf reports by default

diff --git a/scripts/dbt7-report.in b/scripts/dbt7-report.in
--- a/scripts/dbt7-report.in
+++ b/scripts/dbt7-report.in
@@ -350,27 +350,30 @@ if [ ! "x${RST2HTML5}" = "x" ]; then
 	ls -1v ${OUTDIR}/*.html
 	echo ""
 
-	# A pdf could be produced other ways, but I believe pandoc produces the most
-	# minimally styled LaTeX looking document, as opposed to using rst2latex,
-    # with default settings.
-	which pandoc > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		(cd $OUTDIR && \
-				pandoc -s report.html -f html -t pdf \
-						-o report.pdf 2> /dev/null)
-		for HTML in $(find $INDIR -name "*.html"); do
-			NAME="${HTML%.*}"
-			(cd $(dirname $HTML) && \
-					pandoc -s $(basename $HTML) -f html -t pdf \
-							-o ${NAME}.pdf 2> /dev/null)
-		done
+	if [ "${GENERATE_PDF}" = "1" ]; then
+		# A pdf could be produced other ways, but I believe pandoc produces the
+		# most minimally styled LaTeX looking document, as opposed to using
+		# rst2latex, with default settings.
+		which pandoc > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			(cd $OUTDIR && \
+					pandoc -s report.html -f html -t pdf \
+							-o report.pdf 2> /dev/null) &
+			for HTML in $(find $INDIR -name "*.html"); do
+				NAME="${HTML%.*}"
+				(cd $(dirname $HTML) && \
+						pandoc -s $(basename $HTML) -f html -t pdf \
+								-o ${NAME}.pdf 2> /dev/null) &
+			done
+			wait
 
-		echo "Generated PDF reports:"
-		ls -1v ${OUTDIR}/*.pdf
-		echo ""
-	else
-		echo "pandoc required to generate pdf report"
-		exit 1
+			echo "Generated PDF reports:"
+			ls -1v ${OUTDIR}/*.pdf
+			echo ""
+		else
+			echo "pandoc required to generate pdf report"
+			exit 1
+		fi
 	fi
 else
 	echo "rst2html5 required to generate html report"
